### ISSUE TITLE
Any interest in migrating this into ros-perception projects?

### ISSUE THREAD

**Issue by SteveMacenski** [unr-arl/open3d_ros#6]
Hi,

I'm a maintainer on https://github.com/ros-perception/perception_pcl (amongst others in the navigation ecosystem) and I was curious if you had interest in moving this work over to ros-perception and having it released as binaries. This seems to have a great deal of general re-use and would potentially be good to have in the core ecosystem.

Let me know what you think, no pressure. 2 options I'd considered:
- Rename perception_pcl to perception_3d and include this as open3d_conversions analog to pcl_conversions
- New repo with this work in it, perhaps including anything else you were looking to make with this (nodelets like pcl_ros, other conversions, etc)

Regardless, this would be useful to post on ROS Discourse to let people know about it.

**Comment by nkhedekar** [comment]
Hi @SteveMacenski ,

Thank you for reaching out. We agree it would be great to have this code in ros-perception and are open to moving it. We think the first option you have proposed would be better. Consequently, we can first move the code and then post on ROS discourse to prevent confusion. 

As renaming in perception_pcl may break stuff downstream, how should we go about this ?

**Comment by SteveMacenski** [comment]
https://github.com/ros-perception/perception_pcl/issues/291 I filed this ticket to follow up with the community to get the OK from other folks to continue with it. 

In the mean-time, you could submit a PR with the `open3d_conversions` package to `perception_pcl` for people to look at while we discuss. If its approved, I can merge it and rename the repository to highlight the expanded scope of the project

**Comment by nkhedekar** [comment]
Sounds good :+1:

**Comment by SteveMacenski** [comment]
Curious - did you intend to do much more with this (adding nodelets / other integrations)? This by itself is enough to be added (hopefully you'd be willing to continue being a maintainer!), just curios.

**Comment by nkhedekar** [comment]
We did, but not necessarily immediately as the functions currently present in this package satisfied our requirements to work with Open3D. And we are willing to continue being maintainers :slightly_smiling_face:

**Comment by SteveMacenski** [comment]
Awesome, makes sense :+1:

**Comment by SteveMacenski** [comment]
We  can continue discussion in the new repo!
